### ISSUE TITLE
0.8.0 fails to build on Yosemite 10.10.2

### ISSUE THREAD

**Issue by tko** [mpv-player/homebrew-mpv#51]
I've 0.7.3 currently installed and haven't had any trouble installing that or several earlier versions, but now upgrading to 0.8.0 errors out with:
```
[239/242] Linking build/mpv
Undefined symbols for architecture x86_64:
  "_CVDisplayLinkCreateWithCGDisplay", referenced from:
      _vo_cocoa_update_screen_info in cocoa_common.m.13.o
  "_CVDisplayLinkGetNominalOutputVideoRefreshPeriod", referenced from:
      _vo_cocoa_update_screen_info in cocoa_common.m.13.o
  "_CVDisplayLinkRelease", referenced from:
      _vo_cocoa_update_screen_info in cocoa_common.m.13.o
ld: symbol(s) not found for architecture x86_64
```
Found a similar error reported in https://github.com/memononen/fontstash/issues/13 which suggests `CoreVideo` may be missing. Seems plausible reason looking at the linker flags:
```
-o /private/tmp/mpv-WxJygL/mpv-0.8.0/build/mpv
-framework Cocoa
-framework IOKit
-framework OpenGL
-framework CoreFoundation
-framework CoreAudio
-framework AudioUnit
-framework AudioToolbox
-L/usr/local/Cellar/little-cms2/2.6/lib
-L/usr/local/Cellar/ffmpeg/HEAD/lib
-L/usr/local/Cellar/ffmpeg/HEAD/lib
-L/opt/X11/lib
-L/usr/local/Cellar/ffmpeg/HEAD/lib
-L/usr/local/Cellar/mpg123/1.21.0/lib
-L/opt/X11/lib
-L/usr/local/Cellar/ffmpeg/HEAD/lib
-L/opt/X11/lib
-L/opt/X11/lib
-L/opt/X11/lib
-L/usr/local/lib
-L/opt/X11/lib
-L/usr/local/Cellar/libass-ct/HEAD/lib
-llcms2
-ljpeg
-lswresample
-lavutil
-lavcodec
-lavformat
-lswscale
-lXv
-liconv
-lavfilter
-lmpg123
-lm
-lXinerama
-lavdevice
-lXrandr
-lXss
-lz
-lXext
-llua
-lm
-lX11
-lGL
-lass
-isystem/usr/local/include
-isystem/usr/include/libxml2
-isystem/opt/X11/include
-isystem/opt/X11/include/freetype2
-isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
-I/usr/local/opt/gettext/include
-I/usr/local/opt/icu4c/include
-I/usr/local/opt/libass-ct/include
-L/usr/local/opt/gettext/lib
-L/usr/local/opt/libffi/lib
-L/usr/local/opt/icu4c/lib
-L/usr/local/opt/libass-ct/lib
-L/usr/local/lib
-L/opt/X11/lib
-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
-Wl,-headerpad_max_install_names
```

**Comment by pigoz** [comment]
Fixed in https://github.com/mpv-player/mpv/commit/8e80b3fd2fea8bf11abaeb108d85b2bdfbe14695

Will be included in 0.8.1 as well.
